//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

public class _Page_Index_cshtml : System.Web.WebPages.WebPage {
private static object @__o;
#line hidden
public _Page_Index_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\Admin\AppData\Local\Temp\F9910055EB23FDC608697310D56342B4B996\2\BeekeepingStore\eUseControl.BeekeepingStore\Views\Home\Index.cshtml"
  
    Layout = null;


#line default
#line hidden

#line 2 "C:\Users\Admin\AppData\Local\Temp\F9910055EB23FDC608697310D56342B4B996\2\BeekeepingStore\eUseControl.BeekeepingStore\Views\Home\Index.cshtml"
            __o = Url.Action("Index","Home");


#line default
#line hidden

#line 3 "C:\Users\Admin\AppData\Local\Temp\F9910055EB23FDC608697310D56342B4B996\2\BeekeepingStore\eUseControl.BeekeepingStore\Views\Home\Index.cshtml"
            __o = Url.Action("Products","Home");


#line default
#line hidden

#line 4 "C:\Users\Admin\AppData\Local\Temp\F9910055EB23FDC608697310D56342B4B996\2\BeekeepingStore\eUseControl.BeekeepingStore\Views\Home\Index.cshtml"
            __o = Url.Action("Contact","Home");


#line default
#line hidden
}
}
}
